[2025-05-23T04:14:37.059-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-23T04:14:37.064-0400] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project_pipeline.start_redis_store scheduled__2025-05-22T00:00:00+00:00 [queued]>
[2025-05-23T04:14:37.066-0400] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project_pipeline.start_redis_store scheduled__2025-05-22T00:00:00+00:00 [queued]>
[2025-05-23T04:14:37.067-0400] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-05-23T04:14:37.074-0400] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): start_redis_store> on 2025-05-22 00:00:00+00:00
[2025-05-23T04:14:37.086-0400] {standard_task_runner.py:72} INFO - Started process 1147460 to run task
[2025-05-23T04:14:37.092-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'final_project_pipeline', 'start_redis_store', 'scheduled__2025-05-22T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmp8bzu_hn1']
[2025-05-23T04:14:37.093-0400] {standard_task_runner.py:105} INFO - Job 17: Subtask start_redis_store
[2025-05-23T04:14:37.128-0400] {task_command.py:467} INFO - Running <TaskInstance: final_project_pipeline.start_redis_store scheduled__2025-05-22T00:00:00+00:00 [running]> on host Nirbisha.Nirbisha
[2025-05-23T04:14:37.203-0400] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nirbisha.shrestha@mail.bcu.ac.uk' AIRFLOW_CTX_DAG_OWNER='Nirbisha Shrestha' AIRFLOW_CTX_DAG_ID='final_project_pipeline' AIRFLOW_CTX_TASK_ID='start_redis_store' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-22T00:00:00+00:00'
[2025-05-23T04:14:37.205-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-23T04:14:37.205-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-23T04:14:37.205-0400] {logging_mixin.py:190} INFO - Current task name:start_redis_store state:running start_date:2025-05-23 08:14:37.064510+00:00
[2025-05-23T04:14:37.205-0400] {logging_mixin.py:190} INFO - Dag name:final_project_pipeline and current dag run status:running
[2025-05-23T04:14:37.205-0400] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-23T04:14:37.206-0400] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-05-23T04:14:37.206-0400] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker start redis_store']
[2025-05-23T04:14:37.219-0400] {subprocess.py:99} INFO - Output:
[2025-05-23T04:14:37.253-0400] {subprocess.py:106} INFO - Error response from daemon: No such container: redis_store
[2025-05-23T04:14:37.253-0400] {subprocess.py:106} INFO - Error: failed to start containers: redis_store
[2025-05-23T04:14:37.254-0400] {subprocess.py:110} INFO - Command exited with return code 1
[2025-05-23T04:14:37.259-0400] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-23T04:14:37.262-0400] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-23T04:14:37.262-0400] {logging_mixin.py:190} INFO - Task start:2025-05-23 08:14:37.064510+00:00 end:2025-05-23 08:14:37.262180+00:00 duration:0.19767
[2025-05-23T04:14:37.262-0400] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): start_redis_store> dag:<DAG: final_project_pipeline> dagrun:<DagRun final_project_pipeline @ 2025-05-22 00:00:00+00:00: scheduled__2025-05-22T00:00:00+00:00, state:running, queued_at: 2025-05-23 08:14:28.518113+00:00. externally triggered: False>
[2025-05-23T04:14:37.262-0400] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-05-23T04:14:37.263-0400] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=final_project_pipeline, task_id=start_redis_store, run_id=scheduled__2025-05-22T00:00:00+00:00, execution_date=20250522T000000, start_date=20250523T081437, end_date=20250523T081437
[2025-05-23T04:14:37.275-0400] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-23T04:14:37.276-0400] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task start_redis_store (Bash command failed. The command returned a non-zero exit code 1.; 1147460)
Traceback (most recent call last):
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nirbisha/miniforge3/envs/heart_data/lib/python3.8/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-23T04:14:37.304-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-23T04:14:37.318-0400] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-23T04:14:37.321-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
